export default [
  { id: 1, color: 'd' },
  { id: 2, color: 'e' },
  { id: 3, color: 'f' },
  { id: 4, color: 'g' },
  { id: 5, color: 'h' },
  { id: 6, color: 'i' },
  { id: 7, color: 'j' },
  { id: 8, color: 'k' },
  { id: 9, color: 'l' },
  { id: 10, color: 'm' },
  { id: 11, color: 'n' },
  { id: 12, color: 'o' },
  { id: 13, color: 'p' },
  { id: 14, color: 'q' },
  { id: 15, color: 'r' },
  { id: 16, color: 's' },
  { id: 17, color: 't' },
  { id: 18, color: 'u' },
  { id: 19, color: 'v' },
  { id: 20, color: 'w' },
  { id: 21, color: 'x' },
  { id: 22, color: 'y' },
  { id: 23, color: 'z' },
];
