export default [
  {
    id: 1,
    name: 'Afghanistan',
    code: 'AF',
    dial_code: '+93',
    currency: 'AFN',
  },
  {
    id: 2,
    name: 'Albania',
    code: 'AL',
    dial_code: '+355',
    currency: 'ALL',
  },
  {
    id: 3,
    name: 'Algeria',
    code: 'DZ',
    dial_code: '+213',
    currency: 'DZD',
  },
  {
    id: 4,
    name: 'Andorra',
    code: 'AD',
    dial_code: '+376',
    currency: 'EUR',
  },
  {
    id: 5,
    name: 'Angola',
    code: 'AO',
    dial_code: '+244',
    currency: 'AOA',
  },
  {
    id: 6,
    name: 'Argentina',
    code: 'AR',
    dial_code: '+54',
    currency: 'ARS',
  },
  {
    id: 7,
    name: 'Armenia',
    code: 'AM',
    dial_code: '+374',
    currency: 'AMD',
  },
  {
    id: 8,
    name: 'Australia',
    code: 'AU',
    dial_code: '+61',
    currency: 'AUD',
  },
  {
    id: 9,
    name: 'Austria',
    code: 'AT',
    dial_code: '+43',
    currency: 'EUR',
  },
  {
    id: 10,
    name: 'Azerbaijan',
    code: 'AZ',
    dial_code: '+994',
    currency: 'AZN',
  },
  {
    id: 11,
    name: 'Bahamas',
    code: 'BS',
    dial_code: '+1-242',
    currency: 'BSD',
  },
  {
    id: 12,
    name: 'Bahrain',
    code: 'BH',
    dial_code: '+973',
    currency: 'BHD',
  },
  {
    id: 13,
    name: 'Bangladesh',
    code: 'BD',
    dial_code: '+880',
    currency: 'BDT',
  },
  {
    id: 14,
    name: 'Belgium',
    code: 'BE',
    dial_code: '+32',
    currency: 'EUR',
  },
  {
    id: 15,
    name: 'Brazil',
    code: 'BR',
    dial_code: '+55',
    currency: 'BRL',
  },
  {
    id: 16,
    name: 'Bulgaria',
    code: 'BG',
    dial_code: '+359',
    currency: 'BGN',
  },
  {
    id: 17,
    name: 'Canada',
    code: 'CA',
    dial_code: '+1',
    currency: 'CAD',
  },
  {
    id: 18,
    name: 'Chile',
    code: 'CL',
    dial_code: '+56',
    currency: 'CLP',
  },
  {
    id: 19,
    name: 'China',
    code: 'CN',
    dial_code: '+86',
    currency: 'CNY',
  },
  {
    id: 20,
    name: 'Colombia',
    code: 'CO',
    dial_code: '+57',
    currency: 'COP',
  },
  {
    id: 21,
    name: 'Croatia',
    code: 'HR',
    dial_code: '+385',
    currency: 'EUR',
  },
  {
    id: 22,
    name: 'Cuba',
    code: 'CU',
    dial_code: '+53',
    currency: 'CUP',
  },
  {
    id: 23,
    name: 'Cyprus',
    code: 'CY',
    dial_code: '+357',
    currency: 'EUR',
  },
  {
    id: 24,
    name: 'Czech Republic',
    code: 'CZ',
    dial_code: '+420',
    currency: 'CZK',
  },
  {
    id: 25,
    name: 'Denmark',
    code: 'DK',
    dial_code: '+45',
    currency: 'DKK',
  },
  {
    id: 26,
    name: 'Egypt',
    code: 'EG',
    dial_code: '+20',
    currency: 'EGP',
  },
  {
    id: 27,
    name: 'Estonia',
    code: 'EE',
    dial_code: '+372',
    currency: 'EUR',
  },
  {
    id: 28,
    name: 'Finland',
    code: 'FI',
    dial_code: '+358',
    currency: 'EUR',
  },
  {
    id: 29,
    name: 'France',
    code: 'FR',
    dial_code: '+33',
    currency: 'EUR',
  },
  {
    id: 30,
    name: 'Germany',
    code: 'DE',
    dial_code: '+49',
    currency: 'EUR',
  },
  {
    id: 31,
    name: 'Greece',
    code: 'GR',
    dial_code: '+30',
    currency: 'EUR',
  },
  {
    id: 32,
    name: 'Hungary',
    code: 'HU',
    dial_code: '+36',
    currency: 'HUF',
  },
  {
    id: 33,
    name: 'Iceland',
    code: 'IS',
    dial_code: '+354',
    currency: 'ISK',
  },
  {
    id: 34,
    name: 'India',
    code: 'IN',
    dial_code: '+91',
    currency: 'INR',
  },
  {
    id: 35,
    name: 'Indonesia',
    code: 'ID',
    dial_code: '+62',
    currency: 'IDR',
  },
  {
    id: 36,
    name: 'Iran',
    code: 'IR',
    dial_code: '+98',
    currency: 'IRR',
  },
  {
    id: 37,
    name: 'Iraq',
    code: 'IQ',
    dial_code: '+964',
    currency: 'IQD',
  },
  {
    id: 38,
    name: 'Ireland',
    code: 'IE',
    dial_code: '+353',
    currency: 'EUR',
  },
  {
    id: 39,
    name: 'Israel',
    code: 'IL',
    dial_code: '+972',
    currency: 'ILS',
  },
  {
    id: 40,
    name: 'Italy',
    code: 'IT',
    dial_code: '+39',
    currency: 'EUR',
  },
  {
    id: 41,
    name: 'Japan',
    code: 'JP',
    dial_code: '+81',
    currency: 'JPY',
  },
  {
    id: 42,
    name: 'Jordan',
    code: 'JO',
    dial_code: '+962',
    currency: 'JOD',
  },
  {
    id: 43,
    name: 'Kenya',
    code: 'KE',
    dial_code: '+254',
    currency: 'KES',
  },
  {
    id: 44,
    name: 'Kuwait',
    code: 'KW',
    dial_code: '+965',
    currency: 'KWD',
  },
  {
    id: 45,
    name: 'Latvia',
    code: 'LV',
    dial_code: '+371',
    currency: 'EUR',
  },
  {
    id: 46,
    name: 'Lebanon',
    code: 'LB',
    dial_code: '+961',
    currency: 'LBP',
  },
  {
    id: 47,
    name: 'Lithuania',
    code: 'LT',
    dial_code: '+370',
    currency: 'EUR',
  },
  {
    id: 48,
    name: 'Luxembourg',
    code: 'LU',
    dial_code: '+352',
    currency: 'EUR',
  },
  {
    id: 49,
    name: 'Malaysia',
    code: 'MY',
    dial_code: '+60',
    currency: 'MYR',
  },
  {
    id: 50,
    name: 'Mexico',
    code: 'MX',
    dial_code: '+52',
    currency: 'MXN',
  },
  {
    id: 51,
    name: 'Monaco',
    code: 'MC',
    dial_code: '+377',
    currency: 'EUR',
  },
  {
    id: 52,
    name: 'Mongolia',
    code: 'MN',
    dial_code: '+976',
    currency: 'MNT',
  },
  {
    id: 53,
    name: 'Morocco',
    code: 'MA',
    dial_code: '+212',
    currency: 'MAD',
  },
  {
    id: 54,
    name: 'Nepal',
    code: 'NP',
    dial_code: '+977',
    currency: 'NPR',
  },
  {
    id: 55,
    name: 'Netherlands',
    code: 'NL',
    dial_code: '+31',
    currency: 'EUR',
  },
  {
    id: 56,
    name: 'New Zealand',
    code: 'NZ',
    dial_code: '+64',
    currency: 'NZD',
  },
  {
    id: 57,
    name: 'Nigeria',
    code: 'NG',
    dial_code: '+234',
    currency: 'NGN',
  },
  {
    id: 58,
    name: 'North Korea',
    code: 'KP',
    dial_code: '+850',
    currency: 'KPW',
  },
  {
    id: 59,
    name: 'Norway',
    code: 'NO',
    dial_code: '+47',
    currency: 'NOK',
  },
  {
    id: 60,
    name: 'Oman',
    code: 'OM',
    dial_code: '+968',
    currency: 'OMR',
  },
  {
    id: 61,
    name: 'Pakistan',
    code: 'PK',
    dial_code: '+92',
    currency: 'PKR',
  },
  {
    id: 62,
    name: 'Palestine',
    code: 'PS',
    dial_code: '+970',
    currency: 'ILS',
  },
  {
    id: 63,
    name: 'Panama',
    code: 'PA',
    dial_code: '+507',
    currency: 'PAB',
  },
  {
    id: 64,
    name: 'Peru',
    code: 'PE',
    dial_code: '+51',
    currency: 'PEN',
  },
  {
    id: 65,
    name: 'Philippines',
    code: 'PH',
    dial_code: '+63',
    currency: 'PHP',
  },
  {
    id: 66,
    name: 'Poland',
    code: 'PL',
    dial_code: '+48',
    currency: 'PLN',
  },
  {
    id: 67,
    name: 'Portugal',
    code: 'PT',
    dial_code: '+351',
    currency: 'EUR',
  },
  {
    id: 68,
    name: 'Qatar',
    code: 'QA',
    dial_code: '+974',
    currency: 'QAR',
  },
  {
    id: 69,
    name: 'Romania',
    code: 'RO',
    dial_code: '+40',
    currency: 'RON',
  },
  {
    id: 70,
    name: 'Russia',
    code: 'RU',
    dial_code: '+7',
    currency: 'RUB',
  },
  {
    id: 71,
    name: 'Saudi Arabia',
    code: 'SA',
    dial_code: '+966',
    currency: 'SAR',
  },
  {
    id: 72,
    name: 'Serbia',
    code: 'RS',
    dial_code: '+381',
    currency: 'RSD',
  },
  {
    id: 73,
    name: 'Singapore',
    code: 'SG',
    dial_code: '+65',
    currency: 'SGD',
  },
  {
    id: 74,
    name: 'Slovakia',
    code: 'SK',
    dial_code: '+421',
    currency: 'EUR',
  },
  {
    id: 75,
    name: 'Slovenia',
    code: 'SI',
    dial_code: '+386',
    currency: 'EUR',
  },
  {
    id: 76,
    name: 'South Africa',
    code: 'ZA',
    dial_code: '+27',
    currency: 'ZAR',
  },
  {
    id: 77,
    name: 'South Korea',
    code: 'KR',
    dial_code: '+82',
    currency: 'KRW',
  },
  {
    id: 78,
    name: 'Spain',
    code: 'ES',
    dial_code: '+34',
    currency: 'EUR',
  },
  {
    id: 79,
    name: 'Sri Lanka',
    code: 'LK',
    dial_code: '+94',
    currency: 'LKR',
  },
  {
    id: 80,
    name: 'Sudan',
    code: 'SD',
    dial_code: '+249',
    currency: 'SDG',
  },
  {
    id: 81,
    name: 'Sweden',
    code: 'SE',
    dial_code: '+46',
    currency: 'SEK',
  },
  {
    id: 82,
    name: 'Switzerland',
    code: 'CH',
    dial_code: '+41',
    currency: 'CHF',
  },
  {
    id: 83,
    name: 'Syria',
    code: 'SY',
    dial_code: '+963',
    currency: 'SYP',
  },
  {
    id: 84,
    name: 'Thailand',
    code: 'TH',
    dial_code: '+66',
    currency: 'THB',
  },
  {
    id: 85,
    name: 'Turkey',
    code: 'TR',
    dial_code: '+90',
    currency: 'TRY',
  },
  {
    id: 86,
    name: 'Ukraine',
    code: 'UA',
    dial_code: '+380',
    currency: 'UAH',
  },
  {
    id: 87,
    name: 'United Arab Emirates',
    code: 'AE',
    dial_code: '+971',
    currency: 'AED',
  },
  {
    id: 88,
    name: 'United Kingdom',
    code: 'GB',
    dial_code: '+44',
    currency: 'GBP',
  },
  {
    id: 89,
    name: 'United States',
    code: 'US',
    dial_code: '+1',
    currency: 'USD',
  },
  {
    id: 90,
    name: 'Uruguay',
    code: 'UY',
    dial_code: '+598',
    currency: 'UYU',
  },
  {
    id: 91,
    name: 'Uzbekistan',
    code: 'UZ',
    dial_code: '+998',
    currency: 'UZS',
  },
  {
    id: 92,
    name: 'Venezuela',
    code: 'VE',
    dial_code: '+58',
    currency: 'VES',
  },
  {
    id: 93,
    name: 'Vietnam',
    code: 'VN',
    dial_code: '+84',
    currency: 'VND',
  },
  {
    id: 94,
    name: 'Yemen',
    code: 'YE',
    dial_code: '+967',
    currency: 'YER',
  },
  {
    id: 95,
    name: 'Zimbabwe',
    code: 'ZW',
    dial_code: '+263',
    currency: 'ZWL',
  },
];
