export default [
  { id: 1, country_name: 'Afghanistan', code: 'AF', dial_code: '+93' },
  { id: 2, country_name: 'Albania', code: 'AL', dial_code: '+355' },
  { id: 3, country_name: 'Algeria', code: 'DZ', dial_code: '+213' },
  { id: 4, country_name: 'Andorra', code: 'AD', dial_code: '+376' },
  { id: 5, country_name: 'Angola', code: 'AO', dial_code: '+244' },
  { id: 6, country_name: 'Argentina', code: 'AR', dial_code: '+54' },
  { id: 7, country_name: 'Armenia', code: 'AM', dial_code: '+374' },
  { id: 8, country_name: 'Australia', code: 'AU', dial_code: '+61' },
  { id: 9, country_name: 'Austria', code: 'AT', dial_code: '+43' },
  { id: 10, country_name: 'Azerbaijan', code: 'AZ', dial_code: '+994' },
  { id: 11, country_name: 'Bahamas', code: 'BS', dial_code: '+1-242' },
  { id: 12, country_name: 'Bahrain', code: 'BH', dial_code: '+973' },
  { id: 13, country_name: 'Bangladesh', code: 'BD', dial_code: '+880' },
  { id: 14, country_name: 'Belgium', code: 'BE', dial_code: '+32' },
  { id: 15, country_name: 'Brazil', code: 'BR', dial_code: '+55' },
  { id: 16, country_name: 'Bulgaria', code: 'BG', dial_code: '+359' },
  { id: 17, country_name: 'Canada', code: 'CA', dial_code: '+1' },
  { id: 18, country_name: 'Chile', code: 'CL', dial_code: '+56' },
  { id: 19, country_name: 'China', code: 'CN', dial_code: '+86' },
  { id: 20, country_name: 'Colombia', code: 'CO', dial_code: '+57' },
  { id: 21, country_name: 'Croatia', code: 'HR', dial_code: '+385' },
  { id: 22, country_name: 'Cuba', code: 'CU', dial_code: '+53' },
  { id: 23, country_name: 'Cyprus', code: 'CY', dial_code: '+357' },
  { id: 24, country_name: 'Czech Republic', code: 'CZ', dial_code: '+420' },
  { id: 25, country_name: 'Denmark', code: 'DK', dial_code: '+45' },
  { id: 26, country_name: 'Egypt', code: 'EG', dial_code: '+20' },
  { id: 27, country_name: 'Estonia', code: 'EE', dial_code: '+372' },
  { id: 28, country_name: 'Finland', code: 'FI', dial_code: '+358' },
  { id: 29, country_name: 'France', code: 'FR', dial_code: '+33' },
  { id: 30, country_name: 'Germany', code: 'DE', dial_code: '+49' },
  { id: 31, country_name: 'Greece', code: 'GR', dial_code: '+30' },
  { id: 32, country_name: 'Hungary', code: 'HU', dial_code: '+36' },
  { id: 33, country_name: 'Iceland', code: 'IS', dial_code: '+354' },
  { id: 34, country_name: 'India', code: 'IN', dial_code: '+91' },
  { id: 35, country_name: 'Indonesia', code: 'ID', dial_code: '+62' },
  { id: 36, country_name: 'Iran', code: 'IR', dial_code: '+98' },
  { id: 37, country_name: 'Iraq', code: 'IQ', dial_code: '+964' },
  { id: 38, country_name: 'Ireland', code: 'IE', dial_code: '+353' },
  { id: 39, country_name: 'Israel', code: 'IL', dial_code: '+972' },
  { id: 40, country_name: 'Italy', code: 'IT', dial_code: '+39' },
  { id: 41, country_name: 'Japan', code: 'JP', dial_code: '+81' },
  { id: 42, country_name: 'Jordan', code: 'JO', dial_code: '+962' },
  { id: 43, country_name: 'Kenya', code: 'KE', dial_code: '+254' },
  { id: 44, country_name: 'Kuwait', code: 'KW', dial_code: '+965' },
  { id: 45, country_name: 'Latvia', code: 'LV', dial_code: '+371' },
  { id: 46, country_name: 'Lebanon', code: 'LB', dial_code: '+961' },
  { id: 47, country_name: 'Lithuania', code: 'LT', dial_code: '+370' },
  { id: 48, country_name: 'Luxembourg', code: 'LU', dial_code: '+352' },
  { id: 49, country_name: 'Malaysia', code: 'MY', dial_code: '+60' },
  { id: 50, country_name: 'Mexico', code: 'MX', dial_code: '+52' },
  { id: 51, country_name: 'Monaco', code: 'MC', dial_code: '+377' },
  { id: 52, country_name: 'Mongolia', code: 'MN', dial_code: '+976' },
  { id: 53, country_name: 'Morocco', code: 'MA', dial_code: '+212' },
  { id: 54, country_name: 'Nepal', code: 'NP', dial_code: '+977' },
  { id: 55, country_name: 'Netherlands', code: 'NL', dial_code: '+31' },
  { id: 56, country_name: 'New Zealand', code: 'NZ', dial_code: '+64' },
  { id: 57, country_name: 'Nigeria', code: 'NG', dial_code: '+234' },
  { id: 58, country_name: 'North Korea', code: 'KP', dial_code: '+850' },
  { id: 59, country_name: 'Norway', code: 'NO', dial_code: '+47' },
  { id: 60, country_name: 'Oman', code: 'OM', dial_code: '+968' },
  { id: 61, country_name: 'Pakistan', code: 'PK', dial_code: '+92' },
  { id: 62, country_name: 'Palestine', code: 'PS', dial_code: '+970' },
  { id: 63, country_name: 'Panama', code: 'PA', dial_code: '+507' },
  { id: 64, country_name: 'Peru', code: 'PE', dial_code: '+51' },
  { id: 65, country_name: 'Philippines', code: 'PH', dial_code: '+63' },
  { id: 66, country_name: 'Poland', code: 'PL', dial_code: '+48' },
  { id: 67, country_name: 'Portugal', code: 'PT', dial_code: '+351' },
  { id: 68, country_name: 'Qatar', code: 'QA', dial_code: '+974' },
  { id: 69, country_name: 'Romania', code: 'RO', dial_code: '+40' },
  { id: 70, country_name: 'Russia', code: 'RU', dial_code: '+7' },
  { id: 71, country_name: 'Saudi Arabia', code: 'SA', dial_code: '+966' },
  { id: 72, country_name: 'Serbia', code: 'RS', dial_code: '+381' },
  { id: 73, country_name: 'Singapore', code: 'SG', dial_code: '+65' },
  { id: 74, country_name: 'Slovakia', code: 'SK', dial_code: '+421' },
  { id: 75, country_name: 'Slovenia', code: 'SI', dial_code: '+386' },
  { id: 76, country_name: 'South Africa', code: 'ZA', dial_code: '+27' },
  { id: 77, country_name: 'South Korea', code: 'KR', dial_code: '+82' },
  { id: 78, country_name: 'Spain', code: 'ES', dial_code: '+34' },
  { id: 79, country_name: 'Sri Lanka', code: 'LK', dial_code: '+94' },
  { id: 80, country_name: 'Sudan', code: 'SD', dial_code: '+249' },
  { id: 81, country_name: 'Sweden', code: 'SE', dial_code: '+46' },
  { id: 82, country_name: 'Switzerland', code: 'CH', dial_code: '+41' },
  { id: 83, country_name: 'Syria', code: 'SY', dial_code: '+963' },
  { id: 84, country_name: 'Thailand', code: 'TH', dial_code: '+66' },
  { id: 85, country_name: 'Turkey', code: 'TR', dial_code: '+90' },
  { id: 86, country_name: 'Ukraine', code: 'UA', dial_code: '+380' },
  {
    id: 87,
    country_name: 'United Arab Emirates',
    code: 'AE',
    dial_code: '+971',
  },
  { id: 88, country_name: 'United Kingdom', code: 'GB', dial_code: '+44' },
  { id: 89, country_name: 'United States', code: 'US', dial_code: '+1' },
  { id: 90, country_name: 'Uruguay', code: 'UY', dial_code: '+598' },
  { id: 91, country_name: 'Uzbekistan', code: 'UZ', dial_code: '+998' },
  { id: 92, country_name: 'Venezuela', code: 'VE', dial_code: '+58' },
  { id: 93, country_name: 'Vietnam', code: 'VN', dial_code: '+84' },
  { id: 94, country_name: 'Yemen', code: 'YE', dial_code: '+967' },
  { id: 95, country_name: 'Zimbabwe', code: 'ZW', dial_code: '+263' },
];
