export default [
  {
    id: 1,
    name: 'dashboard',
    sidebarIndex: 1,
  },
  {
    id: 2,
    name: 'products--product_list',
    sidebarIndex: 2,
    tabbarIndex: 1,
  },
  {
    id: 3,
    name: 'orders',
    sidebarIndex: 4,
  },
  {
    id: 4,
    name: 'customers',
    sidebarIndex: 5,
  },
  {
    id: 5,
    name: 'configuration--customer_masters',
    sidebarIndex: 6,
    tabbarIndex: 1,
  },
  {
    id: 6,
    name: 'employees',
    sidebarIndex: 7,
  },
  {
    id: 7,
    name: 'accounting-supplier_management--supplier_details',
    sidebarIndex: 8,
    sidebarStepOneIndex: 1,
    tabbarIndex: 1,
  },
  {
    id: 8,
    name: 'accounting-customer_management',
    sidebarIndex: 8,
    sidebarStepOneIndex: 2,
  },
  {
    id: 9,
    name: 'accounting-payment_verification',
    sidebarIndex: 8,
    sidebarStepOneIndex: 3,
  },
  {
    id: 10,
    name: 'salesman-user_activity',
    sidebarIndex: 9,
    sidebarStepOneIndex: 1,
  },
  {
    id: 11,
    name: 'salesman-broadcast_messaging',
    sidebarIndex: 9,
    sidebarStepOneIndex: 2,
  },
  {
    id: 12,
    name: 'salesman-shop_details_and_feedback',
    sidebarIndex: 9,
    sidebarStepOneIndex: 3,
  },
  {
    id: 13,
    name: 'logistics-shipping_and_delivery',
    sidebarIndex: 10,
    sidebarStepOneIndex: 1,
  },
  {
    id: 14,
    name: 'logistics-tracking_and_history',
    sidebarIndex: 10,
    sidebarStepOneIndex: 2,
  },
  {
    id: 15,
    name: 'enquiry',
    sidebarIndex: 11,
  },
  {
    id: 16,
    name: 'setting',
    sidebarIndex: 12,
  },
  {
    id: 17,
    name: 'configuration--global',
    sidebarIndex: 6,
    tabbarIndex: 2,
  },
  {
    id: 18,
    name: 'configuration--custom_coupon_code',
    sidebarIndex: 6,
    tabbarIndex: 3,
  },
  {
    id: 19,
    name: 'products--purchase_history',
    sidebarIndex: 2,
    tabbarIndex: 2,
  },
  {
    id: 20,
    name: 'configuration--color',
    sidebarIndex: 6,
    tabbarIndex: 4,
  },
  {
    id: 21,
    name: 'configuration--shape',
    sidebarIndex: 6,
    tabbarIndex: 5,
  },
  {
    id: 22,
    name: 'configuration--sieve_size',
    sidebarIndex: 6,
    tabbarIndex: 6,
  },
  {
    id: 23,
    name: 'configuration--clarity',
    sidebarIndex: 6,
    tabbarIndex: 7,
  },
  {
    id: 24,
    name: 'configuration--supplier_category',
    sidebarIndex: 6,
    tabbarIndex: 8,
  },
  {
    id: 25,
    name: 'configuration--country',
    sidebarIndex: 6,
    tabbarIndex: 9,
  },
  {
    id: 26,
    name: 'configuration--branch',
    sidebarIndex: 6,
    tabbarIndex: 10,
  },
  {
    id: 27,
    name: 'configuration--region',
    sidebarIndex: 6,
    tabbarIndex: 11,
  },
  {
    id: 28,
    name: 'configuration--price_per_carat',
    sidebarIndex: 6,
    tabbarIndex: 12,
  },
  {
    id: 29,
    name: 'configuration--order_status_caption',
    sidebarIndex: 6,
    tabbarIndex: 13,
  }, 
  {
    id: 30,
    name: 'store',
    sidebarIndex: 3,
  },
];
